export default {
  Copy: 'Copy',
  save: 'save',
  Name: 'Name',
  Next: 'Next',
  About: 'About',
  Users: 'Users',
  Phone: 'Phone',
  Inbox: 'Inbox',
  Block: 'Block',
  cancel: 'cancel',
  Verify: 'Verify',
  Logout: 'Logout',
  signIn: 'Sign In',
  Profile: 'Profile',
  WhatsUp: 'WhatsUp',
  Setting: 'Setting',
  Messages: 'messages',
  ChatRoom: 'ChatRooms',
  remeberMe: 'Remember me',
  Delete_Me: 'Delete for me',
  Delete_Chat: 'Delete Chat',
  TypingStatus: 'typingStatus',
  TypingStatus: 'typingStatus',
  phoneNumber: 'Phone Number',
  OTP_Header: 'Enter OTP Code',
  EnterName: 'Enter Your Name',
  signTextPlaceHolder: 'SighIn',
  StartChatting: 'Start Chatting',
  NoChats: "You haven't chat yet",
  code_Sent: 'Code has been send to',
  DeleteEveryOne: 'Delete for everyone',
  sighinHeading: 'Sign in to your account',
  Gallery_Permission: 'Gallery Permission Denied!',
  Image_picker_Error: 'User did not grant library permission.',
  Image_Selection_Alert_Description:
    'In order to choose an image from your gallery please give access to Urban SandBox by clicking on Setting',
};
