export default {
  send: require('../assets/icons/send.png'),
  more: require('../assets/icons/more.png'),
  check: require('../assets/icons/check.png'),
  cross: require('../assets/icons/cancel.png'),
  pencil: require('../assets/icons/pencil.png'),
  search: require('../assets/icons/search.png'),
  edit: require('../assets/icons/edit-text.png'),
  backArrow: require('../assets/icons/back.png'),
  phone: require('../assets/icons/phone-call.png'),
  info: require('../assets/icons/information.png'),
  uncheck: require('../assets/icons/unchecked.png'),
  userNameIcon: require('../assets/icons/user.png'),
  userIcon: require('../assets/icons/userIcon.png'),
  addUserIcon: require('../assets/icons/comment.png'),
  Background: require('../assets/images/Background.png'),
  spalshImg: require('../assets/images/chatSplashScreen.png'),
  backGroundImage: require('../assets/images/DiscussionBg.png'),
};
